0
/var/lib/slurm/slurmd/job05741/slurm_script: line 13: activate: No such file or directory
Starting server on port 8000 with GPU 0
INFO 09-03 15:54:11 api_server.py:339] vLLM API server version 0.5.4
INFO 09-03 15:54:11 api_server.py:340] args: Namespace(host=None, port=8000, uvicorn_log_level='info', allow_credentials=False, allowed_origins=['*'], allowed_methods=['*'], allowed_headers=['*'], api_key=None, lora_modules=None, prompt_adapters=None, chat_template=None, response_role='assistant', ssl_keyfile=None, ssl_certfile=None, ssl_ca_certs=None, ssl_cert_reqs=0, root_path=None, middleware=[], return_tokens_as_token_ids=False, disable_frontend_multiprocessing=False, model='mistralai/Mistral-7B-Instruct-v0.3', tokenizer=None, skip_tokenizer_init=False, revision=None, code_revision=None, tokenizer_revision=None, tokenizer_mode='auto', trust_remote_code=False, download_dir=None, load_format='auto', dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, max_model_len=None, guided_decoding_backend='outlines', distributed_executor_backend=None, worker_use_ray=False, pipeline_parallel_size=1, tensor_parallel_size=1, max_parallel_loading_workers=None, ray_workers_use_nsight=False, block_size=16, enable_prefix_caching=False, disable_sliding_window=False, use_v2_block_manager=False, num_lookahead_slots=0, seed=0, swap_space=4, cpu_offload_gb=0, gpu_memory_utilization=0.9, num_gpu_blocks_override=None, max_num_batched_tokens=None, max_num_seqs=256, max_logprobs=20, disable_log_stats=False, quantization=None, rope_scaling=None, rope_theta=None, enforce_eager=False, max_context_len_to_capture=None, max_seq_len_to_capture=8192, disable_custom_all_reduce=False, tokenizer_pool_size=0, tokenizer_pool_type='ray', tokenizer_pool_extra_config=None, enable_lora=False, max_loras=1, max_lora_rank=16, lora_extra_vocab_size=256, lora_dtype='auto', long_lora_scaling_factors=None, max_cpu_loras=None, fully_sharded_loras=False, enable_prompt_adapter=False, max_prompt_adapters=1, max_prompt_adapter_token=0, device='auto', scheduler_delay_factor=0.0, enable_chunked_prefill=None, speculative_model=None, num_speculative_tokens=None, speculative_draft_tensor_parallel_size=None, speculative_max_model_len=None, speculative_disable_by_batch_size=None, ngram_prompt_lookup_max=None, ngram_prompt_lookup_min=None, spec_decoding_acceptance_method='rejection_sampler', typical_acceptance_sampler_posterior_threshold=None, typical_acceptance_sampler_posterior_alpha=None, disable_logprobs_during_spec_decoding=None, model_loader_extra_config=None, ignore_patterns=[], preemption_mode=None, served_model_name=None, qlora_adapter_name_or_path=None, otlp_traces_endpoint=None, engine_use_ray=False, disable_log_requests=False, max_log_len=None)
WARNING 09-03 15:54:12 config.py:1454] Casting torch.bfloat16 to torch.float16.
INFO 09-03 15:54:12 utils.py:403] Port 5570 is already in use, trying port 5571
INFO 09-03 15:54:12 llm_engine.py:174] Initializing an LLM engine (v0.5.4) with config: model='mistralai/Mistral-7B-Instruct-v0.3', speculative_config=None, tokenizer='mistralai/Mistral-7B-Instruct-v0.3', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, rope_scaling=None, rope_theta=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, quantization_param_path=None, device_config=cuda, decoding_config=DecodingConfig(guided_decoding_backend='outlines'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None), seed=0, served_model_name=mistralai/Mistral-7B-Instruct-v0.3, use_v2_block_manager=False, enable_prefix_caching=False)
INFO 09-03 15:54:14 model_runner.py:720] Starting to load model mistralai/Mistral-7B-Instruct-v0.3...
INFO 09-03 15:54:14 weight_utils.py:225] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:00<00:01,  1.47it/s]
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:01<00:00,  1.31it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.25it/s]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:02<00:00,  1.28it/s]

INFO 09-03 15:56:06 model_runner.py:732] Loading model weights took 13.5083 GB
INFO 09-03 15:56:11 gpu_executor.py:102] # GPU blocks: 12890, # CPU blocks: 2048
INFO 09-03 15:56:13 model_runner.py:1024] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 09-03 15:56:13 model_runner.py:1028] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 09-03 15:56:23 model_runner.py:1225] Graph capturing finished in 10 secs.
WARNING 09-03 15:56:24 serving_embedding.py:171] embedding_mode is False. Embedding API will not work.
INFO 09-03 15:56:24 launcher.py:14] Available routes are:
INFO 09-03 15:56:24 launcher.py:22] Route: /openapi.json, Methods: GET, HEAD
INFO 09-03 15:56:24 launcher.py:22] Route: /docs, Methods: GET, HEAD
INFO 09-03 15:56:24 launcher.py:22] Route: /docs/oauth2-redirect, Methods: GET, HEAD
INFO 09-03 15:56:24 launcher.py:22] Route: /redoc, Methods: GET, HEAD
INFO 09-03 15:56:24 launcher.py:22] Route: /health, Methods: GET
INFO 09-03 15:56:24 launcher.py:22] Route: /tokenize, Methods: POST
INFO 09-03 15:56:24 launcher.py:22] Route: /detokenize, Methods: POST
INFO 09-03 15:56:24 launcher.py:22] Route: /v1/models, Methods: GET
INFO 09-03 15:56:24 launcher.py:22] Route: /version, Methods: GET
INFO 09-03 15:56:24 launcher.py:22] Route: /v1/chat/completions, Methods: POST
INFO 09-03 15:56:24 launcher.py:22] Route: /v1/completions, Methods: POST
INFO 09-03 15:56:24 launcher.py:22] Route: /v1/embeddings, Methods: POST
INFO:     Started server process [3941573]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO 09-03 15:56:24 launcher.py:45] Gracefully stopping http server
INFO 09-03 15:56:24 server.py:209] vLLM ZMQ RPC Server was interrupted.
INFO:     Shutting down
unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-1' coro=<run_server() done, defined at /home/bhou4/.local/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py:338> exception=AttributeError("'Server' object has no attribute 'servers'")>
Traceback (most recent call last):
  File "/home/bhou4/.local/lib/python3.10/site-packages/uvicorn/server.py", line 162, in startup
    server = await loop.create_server(
  File "/home/bhou4/.conda/envs/gap/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8000): address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhou4/.local/lib/python3.10/site-packages/uvicorn/server.py", line 69, in serve
    await self._serve(sockets)
  File "/home/bhou4/.local/lib/python3.10/site-packages/uvicorn/server.py", line 84, in _serve
    await self.startup(sockets=sockets)
  File "/home/bhou4/.local/lib/python3.10/site-packages/uvicorn/server.py", line 172, in startup
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bhou4/.local/lib/python3.10/site-packages/vllm/entrypoints/openai/api_server.py", line 359, in run_server
    await shutdown_task
  File "/home/bhou4/.local/lib/python3.10/site-packages/uvicorn/server.py", line 261, in shutdown
    for server in self.servers:
AttributeError: 'Server' object has no attribute 'servers'
